import { KeyboardSettings, MouseSettings, Macro } from './types';

export const DEFAULT_MOUSE_SETTINGS: MouseSettings = {
  dpiStages: [
    { id: 1, dpi: 400, color: '#ef4444', enabled: true },
    { id: 2, dpi: 800, color: '#00f0ff', enabled: true },
    { id: 3, dpi: 1600, color: '#10b981', enabled: true },
    { id: 4, dpi: 3200, color: '#f59e0b', enabled: true },
    { id: 5, dpi: 5600, color: '#8b5cf6', enabled: true },
    { id: 6, dpi: 26000, color: '#ec4899', enabled: false },
  ],
  currentDpiIndex: 1, // 800 DPI
  pollingRate: 8000,
  lod: '1mm',
  debounceTimeMs: 4,
  motionSync: true,
  angleSnapping: false,
  rippleControl: false,
  buttonMappings: {
    1: { buttonIndex: 1, name: 'Left Click', action: 'click' },
    2: { buttonIndex: 2, name: 'Right Click', action: 'menu' },
    3: { buttonIndex: 3, name: 'Middle Click', action: 'middle' },
    4: { buttonIndex: 4, name: 'Side Back (MB4)', action: 'back' },
    5: { buttonIndex: 5, name: 'Side Forward (MB5)', action: 'forward' },
    6: { buttonIndex: 6, name: 'DPI Cycle', action: 'dpi_cycle' },
  },
  rgb: {
    effect: 'wave',
    brightness: 80,
    speed: 6,
    color: '#00f0ff',
    sleepTimeoutMin: 5,
  },
  batteryLevel: 88,
  isCharging: false,
};

export const DEFAULT_KEYBOARD_SETTINGS: KeyboardSettings = {
  activeProfileIndex: 1,
  activeLayer: 'base',
  batteryLevel: 94,
  isWireless: false,
  profiles: {
    1: {
      id: 1,
      name: 'Competitive FPS',
      rgb: {
        effect: 'wave',
        brightness: 90,
        speed: 7,
        primaryColor: '#00f0ff',
        secondaryColor: '#8b5cf6',
        perKeyColors: {},
      },
      keyMappings: {},
      debounceTimeMs: 2,
      pollingRate: 8000,
      snapTap: {
        enabled: true,
        primaryPair: ['KeyA', 'KeyD'],
        secondaryPair: ['KeyW', 'KeyS'],
        mode: 'last_input_priority',
      },
      actuation: {
        globalActuationMm: 1.0,
        rapidTriggerEnabled: true,
        rapidTriggerPressMm: 0.08,
        rapidTriggerReleaseMm: 0.08,
        perKeyActuation: {
          KeyW: 0.6,
          KeyA: 0.6,
          KeyS: 0.6,
          KeyD: 0.6,
          Space: 1.2,
        },
      },
    },
    2: {
      id: 2,
      name: 'Typing & Work',
      rgb: {
        effect: 'breathing',
        brightness: 70,
        speed: 4,
        primaryColor: '#10b981',
        secondaryColor: '#00f0ff',
        perKeyColors: {},
      },
      keyMappings: {},
      debounceTimeMs: 8,
      pollingRate: 1000,
      snapTap: {
        enabled: false,
        primaryPair: ['KeyA', 'KeyD'],
        secondaryPair: ['KeyW', 'KeyS'],
        mode: 'last_input_priority',
      },
      actuation: {
        globalActuationMm: 2.0,
        rapidTriggerEnabled: false,
        rapidTriggerPressMm: 0.2,
        rapidTriggerReleaseMm: 0.2,
        perKeyActuation: {},
      },
    },
    3: {
      id: 3,
      name: 'Cyber Neon',
      rgb: {
        effect: 'rainbow',
        brightness: 100,
        speed: 8,
        primaryColor: '#ec4899',
        secondaryColor: '#8b5cf6',
        perKeyColors: {},
      },
      keyMappings: {},
      debounceTimeMs: 4,
      pollingRate: 1000,
      snapTap: {
        enabled: true,
        primaryPair: ['KeyA', 'KeyD'],
        secondaryPair: ['KeyW', 'KeyS'],
        mode: 'last_input_priority',
      },
      actuation: {
        globalActuationMm: 1.4,
        rapidTriggerEnabled: true,
        rapidTriggerPressMm: 0.1,
        rapidTriggerReleaseMm: 0.1,
        perKeyActuation: {},
      },
    },
    4: {
      id: 4,
      name: 'Stealth Custom',
      rgb: {
        effect: 'static',
        brightness: 40,
        speed: 1,
        primaryColor: '#ffffff',
        perKeyColors: {},
      },
      keyMappings: {},
      debounceTimeMs: 5,
      pollingRate: 1000,
      snapTap: {
        enabled: false,
        primaryPair: ['KeyA', 'KeyD'],
        secondaryPair: ['KeyW', 'KeyS'],
        mode: 'last_input_priority',
      },
      actuation: {
        globalActuationMm: 1.8,
        rapidTriggerEnabled: false,
        rapidTriggerPressMm: 0.15,
        rapidTriggerReleaseMm: 0.15,
        perKeyActuation: {},
      },
    },
  },
};

export const DEFAULT_MACROS: Macro[] = [
  {
    id: 'macro-1',
    name: 'CS2 Jumpthrow',
    repeatMode: 'once',
    repeatCount: 1,
    events: [
      { id: '1', type: 'keydown', code: 'Space', keyLabel: 'Space' },
      { id: '2', type: 'delay', delayMs: 15 },
      { id: '3', type: 'keydown', code: 'MouseLeft', keyLabel: 'Mouse Left' },
      { id: '4', type: 'delay', delayMs: 20 },
      { id: '5', type: 'keyup', code: 'MouseLeft', keyLabel: 'Mouse Left' },
      { id: '6', type: 'delay', delayMs: 10 },
      { id: '7', type: 'keyup', code: 'Space', keyLabel: 'Space' },
    ],
  },
  {
    id: 'macro-2',
    name: 'Rapid Fire (3-Burst)',
    repeatMode: 'count',
    repeatCount: 3,
    events: [
      { id: '1', type: 'keydown', code: 'MouseLeft', keyLabel: 'Mouse 1' },
      { id: '2', type: 'delay', delayMs: 25 },
      { id: '3', type: 'keyup', code: 'MouseLeft', keyLabel: 'Mouse 1' },
      { id: '4', type: 'delay', delayMs: 50 },
    ],
  },
];
