import { DeviceDefinition } from './types';

export const DARKPROJECT_DEVICES: DeviceDefinition[] = [
  // ================= MICE (PAW3395 / 3311 / 4090 / 8K) =================
  {
    id: 'dp-me4-wireless-8k',
    name: 'Dark Project ME4 Wireless 8K',
    displayName: 'ME4 Wireless (8000Hz)',
    series: 'ModelOV2WiredSeries',
    vendorId: 0x3554,
    productId: 0xFB07,
    deviceType: 'mouse',
    sn: 'DP-M-ME4-8K',
    sensor: 'PAW3395 (Nordic nRF52840 + WCH CH32V305)',
    maxDpi: 26000,
    maxPollingRate: 8000,
    hasRgb: true,
    hasBattery: true,
    isWireless: true,
    hardwareProfilesCount: 4,
  },
  {
    id: 'dp-me4-wireless',
    name: 'Dark Project ME4 Wireless',
    displayName: 'ME4 Wireless',
    series: 'ModelOV2WiredSeries',
    vendorId: 0x3554,
    productId: 0xFB08,
    deviceType: 'mouse',
    sn: 'DP-M-ME4-WL',
    sensor: 'PAW3395 High Precision Optical',
    maxDpi: 26000,
    maxPollingRate: 1000,
    hasRgb: true,
    hasBattery: true,
    isWireless: true,
    hardwareProfilesCount: 4,
  },
  {
    id: 'dp-me4-wired',
    name: 'Dark Project ME4 Wired',
    displayName: 'ME4 Wired Gaming Mouse',
    series: 'ModelOV2WiredSeries',
    vendorId: 0x3554,
    productId: 0xFB09,
    deviceType: 'mouse',
    sn: 'DP-M-ME4-WD',
    sensor: 'PAW3395 Ultra-fast Optical',
    maxDpi: 26000,
    maxPollingRate: 8000,
    hasRgb: true,
    hasBattery: false,
    isWireless: false,
    hardwareProfilesCount: 4,
  },
  {
    id: 'dp-me3-rgb',
    name: 'Dark Project ME3 RGB',
    displayName: 'ME3 RGB Lightweight',
    series: 'ModelOV2WiredSeries',
    vendorId: 0x3554,
    productId: 0xFB06,
    deviceType: 'mouse',
    sn: 'DP-M-ME3-RGB',
    sensor: 'PAW3311 Gaming Sensor',
    maxDpi: 12000,
    maxPollingRate: 1000,
    hasRgb: true,
    hasBattery: false,
    isWireless: false,
    hardwareProfilesCount: 3,
  },

  // ================= KEYBOARDS: CommonKeyboard (GSKY MCU) =================
  {
    id: 'dp-fuji-87-ansi',
    name: 'Dark Project DPKB Fuji 87 ANSI',
    displayName: 'KD87A Fuji (ANSI)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F021',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-fuji-87-iso',
    name: 'Dark Project DPKB Fuji 87 ISO',
    displayName: 'KD87A Fuji (ISO)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F023',
    layoutType: 'iso',
    keyCount: 88,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-violet-87-ansi',
    name: 'Dark Project DPKB Violet 87 ANSI',
    displayName: 'KD87A Violet (ANSI)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F002',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-midnight-87-ansi',
    name: 'Dark Project DPKB Midnight 87 ANSI',
    displayName: 'KD87A Midnight (ANSI)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F005',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-daylight-87-ansi',
    name: 'Dark Project DPKB Daylight 87 ANSI',
    displayName: 'KD87A Daylight (ANSI)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F008',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-bushido-87-ansi',
    name: 'Dark Project DPKB Bushido 87 ANSI',
    displayName: 'KD87A Bushido (ANSI)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F012',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-celestial-87-ansi',
    name: 'Dark Project DPKB Celestial 87 ANSI',
    displayName: 'KD87A Celestial (ANSI)',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE40F,
    deviceType: 'keyboard',
    sn: '0x342D0xE40F015',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-onionite-87-wl',
    name: 'Dark Project DPKB Onionite 87 Wireless',
    displayName: 'KD87A Onionite Wireless',
    series: 'CommonKeyboardSeries',
    vendorId: 0x342D,
    productId: 0xE410,
    deviceType: 'keyboard',
    sn: '0x342D0xE410001',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasBattery: true,
    isWireless: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },

  // ================= KEYBOARDS: SparkLink (Magnetic / Hall Effect) =================
  {
    id: 'dp-gamma-87-he',
    name: 'Dark Project Gamma 87 Magnetic HE',
    displayName: 'Gamma 87 Rapid Trigger (Hall Effect)',
    series: 'SparkLinkSeries',
    vendorId: 0x1CA4,
    productId: 0x0101,
    deviceType: 'keyboard',
    sn: '0x1CA40x0101001',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasRapidTrigger: true,
    hasSnapTap: true,
    hardwareProfilesCount: 4,
  },

  // ================= KEYBOARDS: Witmod (Nuvoton MCU) =================
  {
    id: 'dp-kd87-ink',
    name: 'Dark Project DPP87 GSH Ink ANSI',
    displayName: 'KD87A Ink Black (ANSI)',
    series: 'WitmodSeries',
    vendorId: 0x0416,
    productId: 0xC345,
    deviceType: 'keyboard',
    sn: '0x04160xC345001',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },
  {
    id: 'dp-kd83-navy',
    name: 'Dark Project DPP83 GSH Navy ANSI',
    displayName: 'KD83A Navy 75% (ANSI)',
    series: 'WitmodSeries',
    vendorId: 0x0416,
    productId: 0xC345,
    deviceType: 'keyboard',
    sn: '0x04160xC345003',
    layoutType: 'ansi',
    keyCount: 83,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },

  // ================= KEYBOARDS: TFT Screen Series =================
  {
    id: 'dp-kd98-tft',
    name: 'Dark Project KD98 TFT Display Keyboard',
    displayName: 'KD98 TFT Smart Screen',
    series: 'TFTKeyboardSeries',
    vendorId: 0x05AC,
    productId: 0x024F,
    deviceType: 'keyboard',
    sn: '0x05AC0x024F001',
    layoutType: 'iso',
    keyCount: 98,
    hasRgb: true,
    hasTftScreen: true,
    hasSnapTap: true,
    hardwareProfilesCount: 4,
  },
  {
    id: 'dp-dpone-87',
    name: 'Dark Project Dpone 87 Screen Keyboard',
    displayName: 'Dpone 87 Smart Display',
    series: 'DponeSeries',
    vendorId: 0x1A2C,
    productId: 0x1514,
    deviceType: 'keyboard',
    sn: '0x1A2C0x1514001',
    layoutType: 'ansi',
    keyCount: 87,
    hasRgb: true,
    hasTftScreen: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  },

  // ================= KEYBOARDS: HFDKB / Aluminium / Terra =================
  {
    id: 'dp-terra-nostra',
    name: 'Dark Project Terra Nostra CNC Aluminium',
    displayName: 'Terra Nostra Premium CNC',
    series: 'HFDKBRGBSeries',
    vendorId: 0xFEFE,
    productId: 0x003D,
    deviceType: 'keyboard',
    sn: '0xFEFE0x003D001',
    layoutType: 'ansi',
    keyCount: 83,
    hasRgb: true,
    hasSnapTap: true,
    hardwareProfilesCount: 4,
  },
  {
    id: 'dp-alu85a',
    name: 'Dark Project ALU85A Wireless',
    displayName: 'ALU85A CNC Wireless',
    series: 'HFDKBSeries',
    vendorId: 0x0C45,
    productId: 0x800A,
    deviceType: 'keyboard',
    sn: '0x0C450x800A001',
    layoutType: 'ansi',
    keyCount: 85,
    hasRgb: true,
    hasBattery: true,
    isWireless: true,
    hasSnapTap: true,
    hardwareProfilesCount: 3,
  }
];

export function getDeviceById(id: string): DeviceDefinition | undefined {
  return DARKPROJECT_DEVICES.find((d) => d.id === id);
}

export function findDeviceByUsbIds(vendorId: number, productId: number): DeviceDefinition | undefined {
  return DARKPROJECT_DEVICES.find(
    (d) => d.vendorId === vendorId && d.productId === productId
  );
}
